#!/usr/bin/env bash

# Checks whether or not the command bat exists
# if it does use it as the man pager
if [[ -x "$(command -v "bat")" ]]; then
  export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"
fi

## Requires fzf and bat :P
bat_themes() {
  bat --list-themes | fzf --preview="bat --theme={} --color=always ""$1"
}

