## Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_macchiato"

add_newline = true

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)"        # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[palettes.nord]
# An arctic, north-bluish color palette.
# Created for the clean- and minimal flat design pattern to achieve a optimal focus and readability for code syntax
# highlighting and UI.
# It consists of a total of sixteen, carefully selected, dimmed pastel colors for a eye-comfortable, but yet colorful
# ambiance.
#
# Styleguide Nord
#
# Base component color of "Polar Night".
#
# Used for texts, backgrounds, carets and structuring characters like curly- and square brackets.
#
# Markup:
# <div style="background-color:#2e3440; width=60; height=60"></div>
#
# Styleguide Nord - Polar Night
nord0 = "#2e3440"


# Lighter shade color of the base component color.
#
# Used as a lighter background color for UI elements like status bars.
#
# Markup:
# <div style="background-color:#3b4252; width=60; height=60"></div>
#
# Styleguide Nord - Polar Night
nord1 = "#3b4252"

# Lighter shade color of the base component color.
#
# Used as line highlighting in the editor.
# In the UI scope it may be used as selection- and highlight color.
#
# Markup:
# <div style="background-color:#434c5e; width=60; height=60"></div>
#
# Styleguide Nord - Polar Night
nord2 = "#434c5e"

# Lighter shade color of the base component color.
#
# Used for comments, invisibles, indent- and wrap guide marker.
# In the UI scope used as pseudoclass color for disabled elements.
#
# Markup:
# <div style="background-color:#4c566a; width=60; height=60"></div>
#
# Styleguide Nord - Polar Night
nord3 = "#4c566a"

# // Base component color of "Snow Storm".
# //
# // Main color for text, variables, constants and attributes.
# // In the UI scope used as semi-light background depending on the theme shading design.
# //
# // Markup:
# // <div style="background-color:#d8dee9; width=60; height=60"></div>
# //
# // Styleguide Nord - Snow Storm
nord4 = "#d8dee9"

# // Lighter shade color of the base component color.
# //
# // Used as a lighter background color for UI elements like status bars.
# // Used as semi-light background depending on the theme shading design.
# //
# // Markup:
# // <div style="background-color:#e5e9f0; width=60; height=60"></div>
# //
# // Styleguide Nord - Snow Storm
nord5 = "#e5e9f0"

# Lighter shade color of the base component color.
# 
# Used for punctuations, carets and structuring characters like curly- and square brackets.
# In the UI scope used as background, selection- and highlight color depending on the theme shading design.
# 
# Markup:
# <div style="background-color:#eceff4; width=60; height=60"></div>
# 
# Styleguide Nord - Snow Storm
nord6 = "#eceff4"

# // Bluish core color.
# //
# // Used for classes, types and documentation tags.
# //
# // Markup:
# // <div style="background-color:#8fbcbb; width=60; height=60"></div>
# //
# // Styleguide Nord - Frost
nord7 = "#8fbcbb"

# // Bluish core color.
# //
# // Represents the accent color of the color palette.
# // Main color for primary UI elements and methods/functions.
# //
# // Can be used for
# //   - Markup quotes
# //   - Markup link URLs
# //
# // Markup:
# // <div style="background-color:#88c0d0; width=60; height=60"></div>
# //
# // Styleguide Nord - Frost
nord8 = "#88c0d0"

# // Bluish core color.
# //
# // Used for language-specific syntactic/reserved support characters and keywords, operators, tags, units and
# // punctuations like (semi)colons,commas and braces.
# //
# // Markup:
# // <div style="background-color:#81a1c1; width=60; height=60"></div>
# //
# // Styleguide Nord - Frost
nord9 = "#81a1c1"

# // Bluish core color.
# //
# // Used for markup doctypes, import/include/require statements, pre-processor statements and at-rules (`@`).
# //
# // Markup:
# // <div style="background-color:#5e81ac; width=60; height=60"></div>
# //
# // Styleguide Nord - Frost
nord10 = "#5e81ac"

# // Colorful component color.
# //
# // Used for errors, git/diff deletion and linter marker.
# //
# // Markup:
# // <div style="background-color:#bf616a; width=60; height=60"></div>
# //
# // Styleguide Nord - Aurora
nord11 = "#bf616a"

# // Colorful component color.
# //
# // Used for annotations.
# //
# // Markup:
# // <div style="background-color:#d08770; width=60; height=60"></div>
# //
# // Styleguide Nord - Aurora
nord12 = "#d08770"

# // Colorful component color.
# //
# // Used for escape characters, regular expressions and markup entities.
# // In the UI scope used for warnings and git/diff renamings.
# //
# // Markup:
# // <div style="background-color:#ebcb8b; width=60; height=60"></div>
# //
# // Styleguide Nord - Aurora
nord13 = "#ebcb8b"

# // Colorful component color.
# //
# // Main color for strings and attribute values.
# // In the UI scope used for git/diff additions and success visualizations.
# //
# // Markup:
# // <div style="background-color:#a3be8c; width=60; height=60"></div>
# //
# // Styleguide Nord - Aurora
nord14 = "#a3be8c"

# // Colorful component color.
# //
# // Used for numbers.
# //
# // Markup:
# // <div style="background-color:#b48ead; width=60; height=60"></div>
# //
# // Styleguide Nord - Aurora
nord15 = "#b48ead"
