#!/usr/bin/env bash

#### Ensure this is in your .bashrc and uncommented it could already be there though ^\_(0_0)_/^
# if [ -d ~/.bashrc.d ]; then
#   for rc in ~/.bashrc.d/*; do
#     if [ -f "$rc" ]; then
#       . "$rc"
#     fi
#   done
# fi
# unset rc

export GIT_EDITOR="nvim"

# Example usage of MY_THEME variable
# if [["$MY_THEME" == "catppuccin" ]]; then export BAT_THEME="Catppuccin Mocha" fi
# if [["$MY_THEME" == "nord" ]]; then export BAT_THEME="Nord" fi
# etc...

# Pretty self explanatory...
# Stands for make directory and change directory
mkcd() {
  mkdir "$1" && cd "$1"
}

# Usage Example:
# Put "foo" as the contents of the clipboard
# echo "foo" | pbcopy
alias pbcopy="xclip -selection clipboard"

# Usage Example:
# output contents of clipboard to test.txt
# pbpaste > test.txt
alias pbpaste="xclip -o"
