#!/usr/bin/env bash

#### Ensure this is in your .bashrc and uncommented it could already be there though ^\_(0_0)_/^
# if [ -d ~/.bashrc.d ]; then
#   for rc in ~/.bashrc.d/*; do
#     if [ -f "$rc" ]; then
#       . "$rc"
#     fi
#   done
# fi
# unset rc

export GIT_EDITOR="nvim"

mkcd() {
  mkdir "$1" && cd "$1"
}
