#!/usr/bin/env bash

# https://github.com/catppuccin/fzf
# catppuccin machiatto
if [[ "$MY_THEME" == "catppuccin" ]]; then
  export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#b7bdf8,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--color=selected-bg:#494d64 \
--color=border:#363a4f,label:#cad3f5'
fi

# https://github.com/ianchesal/nord-fzf
# Nord theme
if [[ "$MY_THEME" = "nord" ]]; then
  export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=fg:#e5e9f0,bg:#3b4252,hl:#81a1c1
    --color=fg+:#e5e9f0,bg+:#3b4252,hl+:#81a1c1
    --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
    --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'
fi
